language: cpp
compiler:
  - gcc
dist: trusty

# Could turn on caching - e.g. for building voro++
#cache:
#  directories:
#  - zeopp

env:
  global:
  # add network executable to PATH
  - PATH=${PATH}:${TRAVIS_BUILD_DIR}

install:
  - cd voro++; make; cd -
  - cd zeo++; make; cd -

script:
  - cd tests/ && ./run_tests.sh
