language: cpp
compiler:
  - gcc
dist: trusty

# Could turn on caching - e.g. for building voro++
#cache:
#  directories:
#  - zeopp

env:
  global:
  # add network executable to PATH
  - PATH=${PATH}:${TRAVIS_BUILD_DIR}/zeo++

install:
  - wget https://gitlab.com/libeigen/eigen/-/archive/3.2.7/eigen-3.2.7.tar.bz2
  - tar xf eigen-3.2.7.tar.bz2
  - cd voro++; make; cd -
  - cd zeo++; make; cd -

script:
  - cd tests/ && ./run_tests.sh
